[workspace]
resolver = "3"
members = [
    "engine-core",
    "gateway",
    "market-data",
    "net",
    "persistence",
    "protocol",
    "runtime",
]

[workspace.dependencies]
once_cell = "1.21.3"
tokio = { version = "1.48.0", features = [
    "full",
    "sync",
    "rt",
    "rt-multi-thread",
] }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"
crossbeam-channel = "0.5.15"
oneshot = "0.1.11"
