[package]
name = "protocol"
version = "0.1.0"
edition = "2024"

[dependencies]
enum_stringify = "0.6.4"
oneshot = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
strum = "0.27.2"
